### PR TITLE
integration tests on analyze.* scripts (fixes #16, fixes #17, fixes #100, fixes #101)

### LINKED ISSUE #16: Unit tests for analyze.py
`analyze.py` needs some unit tests. Tests should check in a few JSON files expected to be the result of running `analyze.py` on known packages and then confirm basics about the details. Could use [pkgnet's testing](https://github.com/UptakeOpenSource/pkgnet/tree/master/tests/testthat) for inspiration.

### LINKED ISSUE #17: unit tests for analyze.R
`analyze.R` needs some unit tests. Tests should check in a few JSON files expected to be the result of running `analyze.py` on known packages and then confirm basics about the details. Could use [pkgnet's testing](https://github.com/UptakeOpenSource/pkgnet/tree/master/tests/testthat) for inspiration.

### LINKED ISSUE #100: doppel-describe does not wrap 'args' in an array for single-argument functions (R)
Given a function like:

```{r}
function_c <- function(...){
    return(invisible(NULL))
}
```

running `doppel-describe --language r` on that package will yield something like:

It should be:

```{json}
"function_c": {
      "args": [
        "~~KWARGS~~"
      ]
    }
```

Getting this wrong causes a really tough bug when running `doppel-test`, because this code will think you have 10 arguments (not 1), as a result of how Python iterates over strings:

```{python}
args = [arg for arg in '~~KWARGS~~']

len(args)
10
```

### LINKED ISSUE #101: doppel-describe incorrectly omits python functions that are decorated
Given a function like this:

```{python}
from functools import lru_cache

@lru_cache(maxsize=1)
def function_c(**kwargs):
    pass
```

The code in `analyze.py` incorrectly skips this function and says something like:

> 'function_c' is not a function in this package

This is because the decorator is higher up in the environment and is the object Python sees when running `str(function_c)`.

```{python}
>>> str(function_c)
'<functools._lru_cache_wrapper object at 0x10e8bd588>'
```

To get past this, it's probably necessary to work through the decorators by accessing `obj.__wrapped__` (like what was done with class `methods`). This is a result of treating public methods of classes differently from functions in the code base.

### PR DESCRIPTION
**Pull request by jameslamb**
This PR aims to add a test setup that rigorously validates the behavior of `analyze.py` and `analyze.R`. Up until now, all unit tests have been limited to what `doppel` does _given that `doppel-describe` has been run and produced correct results_.

As of this PR, the correctness of the produced results can also be tested! I've created fake R and python packages that are contrived to produce any and all problems that `doppel-describe` knows how to get around. The intent is to fill these up with test cases over time as more problems are discovered with the `analyze.*` scripts.

This PR also simplifies the structure of the `.ci/` folder.

### CODE REVIEW

File: doppel/bin/analyze.R [hunk 1]
```diff
@@ -102,10 +102,12 @@ for (obj_name in export_names){
...
-            "args" = gsub(
-                "\\.\\.\\."
-                , KWARGS_STRING
-                , names(formals(obj))
+            "args" = as.list(
+                gsub(
+                    "\\.\\.\\."
+                    , KWARGS_STRING
+                    , names(formals(obj))
+                )
```
Comment (jameslamb) [inline doppel/bin/analyze.R]: this is the line that fixes #100

File: doppel/bin/analyze.py [hunk 2]
```diff
@@ -90,13 +104,21 @@ def _get_arg_names(f, kwargs_string):
 
         # Grab the object
         obj = getattr(pkg_env, obj_name)
+        obj = _remove_decorators(obj)
```
Comment (jameslamb) [inline doppel/bin/analyze.py]: doing this fixes #101

File: doppel/reporters.py [hunk 3]
```diff
@@ -3,7 +3,6 @@
 from sys import stdout
 from tabulate import tabulate
 from functools import reduce
-from typing import List
```
Comment (jameslamb) [inline doppel/reporters.py]: cleaning up an unused import while I'm here
